// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gullluryfretqztoobxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bGxsdXJ5ZnJldHF6dG9vYnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzc0NDEsImV4cCI6MjA2Mzk1MzQ0MX0.BusQX88OaZQmsuO6gA_RwiuG5ZohWlv57JvbjXHk0EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);